TodoList.Web/Controllers/AppUserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection.XmlEncryption;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using TodoList.Data;
using TodoList.Models;
using TodoList.Repository.Shared.Abstract;
using TodoList.Repository.Shared.Concrete;

namespace TodoList.Web.Controllers
{
    public class AppUserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AppUserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(AppUser appUser)
        {
            //if( _context.Users.Where(u=>u.UserName==user.UserName && u.Password == user.Password).Count()!=0)
            //{

            //}
            //else
            // {

            // }


            AppUser user = _unitOfWork.AppUsers.GetAll(u => u.Username == appUser.Username && u.Password == appUser.Password).Include(u => u.UserType).First();



            if (user != null)
            {
                //eğer  byle bir kulanıcı varsa login işlemleine başlayabiliriz.

                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Name, user.Username));
                claims.Add(new Claim(ClaimTypes.Role, user.UserType.Name));
                claims.Add(new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()));


                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);


                HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return Ok();
            }
            else
            {
                return BadRequest();
                //böyle bir kullanıcı YOK hatası döndürebiliriz.
            }


        }

        [Authorize(Roles ="Admin")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles ="Admin")]
        public IActionResult GetAll()
        {
            return Json(new {data= _unitOfWork.AppUsers.GetAll(u => u.IsDeleted == false).Include(u => u.UserType).ToList() });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            //AppUser user= _context.Users.Find(id);
            // user.IsDeleted = true;
            // _context.Users.Update(user);
            // _context.SaveChanges();

            _unitOfWork.AppUsers.DeleteById(id);
            _unitOfWork.Save();

            return Ok();
       
        }

        [HttpPost]
        [Authorize(Roles ="Admin")]
        public IActionResult Add(AppUser appUser)
        {
            //_context.Users.Add(appUser);
            //_context.SaveChanges();

            _unitOfWork.AppUsers.Add(appUser);
            _unitOfWork.Save();
            return Ok();
        }

        [HttpPost]
        [Authorize(Roles ="Admin")]
        public IActionResult Update(AppUser appUser)
        {
            //_context.Users.Update(appUser);
            //_context.SaveChanges();

            _unitOfWork.AppUsers.Update(appUser);
            _unitOfWork.Save();
            return Ok();
        }
    }
}

TodoList.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoList.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoList.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />"
    @await RenderSectionAsync("Styles", required: false)
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoList.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="Index">User Management</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TodoList.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>